import { AgentVoiceConfig } from '../data/agents';
import { startTimedVisemes, stopTimedVisemes } from './timedVisemes';

// Global audio element reference so multiple voices don't talk over each other
let currentAudioElement: HTMLAudioElement | null = null;
let currentAudioContext: AudioContext | null = null;
let currentAnalyser: AnalyserNode | null = null;
let currentSourceNode: MediaElementAudioSourceNode | null = null;
let animationFrameId: number | null = null;

// Client-side cooldown timestamp when ElevenLabs voice free tier hits its 3 req/min quota
let clientTTSCooldownUntil = 0;

export interface AudioVisualizerCallback {
  (frequencyData: Uint8Array): void;
}

export function isVoiceProviderInCooldown(): boolean {
  return Date.now() < clientTTSCooldownUntil;
}

export function getRemainingTTSCooldownSeconds(): number {
  return Math.max(0, Math.ceil((clientTTSCooldownUntil - Date.now()) / 1000));
}

/**
 * Play audio from a base64 WAV URL (generated by ElevenLabs voice).
 * Connects to Web Audio API Analyser for visualizer updates.
 */
export async function playProviderAudio(
  audioUrl: string,
  onStart?: () => void,
  onEnd?: () => void,
  onVisualizerFrame?: AudioVisualizerCallback
): Promise<void> {
  stopAllAudio();

  return new Promise((resolve) => {
    try {
      const audio = new Audio(audioUrl);
      currentAudioElement = audio;

      // Setup audio analyzer if supported
      try {
        const AudioCtx = window.AudioContext || (window as any).webkitAudioContext;
        if (AudioCtx) {
          if (!currentAudioContext || currentAudioContext.state === 'closed') {
            currentAudioContext = new AudioCtx();
          }
          if (currentAudioContext.state === 'suspended') {
            currentAudioContext.resume();
          }
          const analyser = currentAudioContext.createAnalyser();
          analyser.fftSize = 64;
          currentAnalyser = analyser;

          const source = currentAudioContext.createMediaElementSource(audio);
          currentSourceNode = source;
          source.connect(analyser);
          analyser.connect(currentAudioContext.destination);

          if (onVisualizerFrame) {
            const dataArray = new Uint8Array(analyser.frequencyBinCount);
            const renderLoop = () => {
              if (currentAudioElement && !currentAudioElement.paused) {
                analyser.getByteFrequencyData(dataArray);
                onVisualizerFrame(new Uint8Array(dataArray));
                animationFrameId = requestAnimationFrame(renderLoop);
              } else {
                onVisualizerFrame(new Uint8Array(analyser.frequencyBinCount));
              }
            };
            audio.onplay = () => {
              if (onStart) onStart();
              renderLoop();
            };
          }
        }
      } catch (err) {
        // AudioContext error shouldn't prevent audio from playing
      }

      audio.onended = () => {
        stopVisualizerLoop();
        if (onEnd) onEnd();
        resolve();
      };

      audio.onerror = () => {
        stopVisualizerLoop();
        if (onEnd) onEnd();
        resolve();
      };

      audio.play().catch(() => {
        if (onEnd) onEnd();
        resolve();
      });
    } catch (e) {
      if (onEnd) onEnd();
      resolve();
    }
  });
}

/**
 * Fallback / Instant Speech using browser Web Speech API.
 * Accurately selects distinct voices and tunes pitch, rate, and accents for each of the 12 agents.
 */
export function speakWebSpeech(
  text: string,
  voiceConfig: AgentVoiceConfig,
  agentId?: string,
  onStart?: () => void,
  onEnd?: () => void,
  onVisualizerFrame?: AudioVisualizerCallback
): void {
  stopAllAudio();

  if (!('speechSynthesis' in window)) {
    if (onEnd) onEnd();
    return;
  }

  // Cancel any ongoing speech
  window.speechSynthesis.cancel();

  const cleanText = text
    .replace(/[*_#`[\]()]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  const utterance = new SpeechSynthesisUtterance(cleanText);
  utterance.pitch = voiceConfig.pitch || 1.0;
  utterance.rate = voiceConfig.rate || 1.0;
  utterance.lang = voiceConfig.webSpeechLang || 'en-US';

  // Stable per-agent browser fallback. Natural server TTS remains preferred;
  // this prevents all 12 characters collapsing onto one generic system voice.
  const voices = window.speechSynthesis.getVoices();
  if (voices.length > 0) {
    const english = voices.filter(v => v.lang.toLowerCase().startsWith('en'));
    const gb = english.filter(v => v.lang.toLowerCase().startsWith('en-gb'));
    const us = english.filter(v => v.lang.toLowerCase().startsWith('en-us'));
    const pool = (agentId === 'simon' || agentId === 'alice') && gb.length ? gb : (us.length ? us : english);
    const preferredIndex: Record<string,number> = {
      simon:0, marie:1, iris:2, mark:3, cammy:4, evan:5,
      tube:6, lucy:7, snake:8, alice:9, echo:10, booker:11
    };
    const named: Record<string,string[]> = {
      simon:['Daniel','George','Oliver','Ryan'], marie:['Samantha','Victoria','Karen','Zira'],
      iris:['Aria','Jenny','Samantha'], mark:['Guy','David','Alex'], cammy:['Jenny','Aria','Zira'],
      evan:['Davis','Alex','Guy'], tube:['Ryan','Eric','David'], lucy:['Samantha','Jenny','Aria'],
      snake:['Daniel','David','Alex'], alice:['Victoria','Jenny','Zira'], echo:['Aria','Samantha','Jenny'],
      booker:['Guy','Davis','Daniel','Alex']
    };
    const names=named[agentId || ''] || [];
    const byName=pool.find(v=>names.some(n=>v.name.toLowerCase().includes(n.toLowerCase())));
    utterance.voice=byName || pool[(preferredIndex[agentId || ''] || 0) % Math.max(pool.length,1)] || english[0];
  }

  let syntheticWaveInterval: any = null;

  utterance.onstart = () => {
    if (onStart) onStart();
    if (onVisualizerFrame) {
      // High-resolution frequency wave simulation for Web Speech
      syntheticWaveInterval = setInterval(() => {
        const fakeData = new Uint8Array(32);
        for (let i = 0; i < fakeData.length; i++) {
          fakeData[i] = Math.floor(Math.random() * 160 + 35);
        }
        onVisualizerFrame(fakeData);
      }, 50);
    }
  };

  utterance.onend = () => {
    if (syntheticWaveInterval) clearInterval(syntheticWaveInterval);
    if (onVisualizerFrame) onVisualizerFrame(new Uint8Array(32));
    if (onEnd) onEnd();
  };

  utterance.onerror = () => {
    if (syntheticWaveInterval) clearInterval(syntheticWaveInterval);
    if (onVisualizerFrame) onVisualizerFrame(new Uint8Array(32));
    if (onEnd) onEnd();
  };

  window.speechSynthesis.speak(utterance);
}

/**
 * Universal speech execution:
 * 1. Checks if client is currently in rate-limit cooldown. If so, immediately uses browser speech without network delay.
 * 2. Attempts ElevenLabs TTS via server.
 * 3. If server reports quota or error, updates cooldown and smoothly falls back to Web Speech.
 */
export async function speakAgent(
  text: string,
  agentId: string,
  voiceConfig: AgentVoiceConfig,
  preferNaturalVoice: boolean = true,
  onStart?: () => void,
  onEnd?: () => void,
  onVisualizerFrame?: AudioVisualizerCallback
): Promise<void> {
  const inCooldown = Date.now() < clientTTSCooldownUntil;

  if (preferNaturalVoice && !inCooldown) {
    try {
      const res = await fetch('/api/agent/speak', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, agentId }),
      });
      const data = await res.json();

      if (data.quotaCooldown) {
        clientTTSCooldownUntil = Date.now() + (data.remainingSeconds || 60) * 1000;
      }

      if (data.audioUrl && !data.fallbackToWebSpeech) {
        if (agentId === 'simon') startTimedVisemes(text);
        await playProviderAudio(data.audioUrl, onStart, () => {
          if (agentId === 'simon') stopTimedVisemes();
          if (onEnd) onEnd();
        }, onVisualizerFrame);
        return;
      }
    } catch {
      // Network failure; fall back smoothly
    }
  }

  // Seamless fallback to customized Web Speech API
  speakWebSpeech(text, voiceConfig, agentId, onStart, onEnd, onVisualizerFrame);
}

export function stopAllAudio(): void {
  stopTimedVisemes();
  if (animationFrameId) {
    cancelAnimationFrame(animationFrameId);
    animationFrameId = null;
  }
  if (currentAudioElement) {
    currentAudioElement.pause();
    currentAudioElement.currentTime = 0;
    currentAudioElement = null;
  }
  if ('speechSynthesis' in window) {
    window.speechSynthesis.cancel();
  }
}

function stopVisualizerLoop(): void {
  if (animationFrameId) {
    cancelAnimationFrame(animationFrameId);
    animationFrameId = null;
  }
}

/**
 * Speech-to-text listener helper using Web Speech Recognition
 */
export function createSpeechRecognizer(
  onTranscript: (text: string) => void,
  onError?: (err: any) => void
): { start: () => void; stop: () => void; isSupported: boolean } {
  const SpeechRecognition =
    (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;

  if (!SpeechRecognition) {
    return {
      start: () => {},
      stop: () => {},
      isSupported: false,
    };
  }

  const recognition = new SpeechRecognition();
  recognition.continuous = false;
  recognition.interimResults = true;
  recognition.lang = 'en-US';

  recognition.onresult = (event: any) => {
    let finalTranscript = '';
    for (let i = event.resultIndex; i < event.results.length; ++i) {
      if (event.results[i].isFinal) {
        finalTranscript += event.results[i][0].transcript;
      }
    }
    if (finalTranscript) {
      onTranscript(finalTranscript);
    }
  };

  recognition.onerror = (e: any) => {
    if (onError) onError(e);
  };

  return {
    start: () => {
      try {
        recognition.start();
      } catch {
        // Recognition start error
      }
    },
    stop: () => {
      try {
        recognition.stop();
      } catch {
        // Recognition stop error
      }
    },
    isSupported: true,
  };
}
